#!/bin/bash
virsh destroy $1
virsh undefine $1
rm -f /virt/runtime/$1.qcow2
echo "$(date -R) Removing ip from dhcp server..."
virsh net-update default delete ip-dhcp-host "<host name='$1' />" --live --config