#!/bin/bash
instances=`virsh list --name`
var=10
for instance in $instances
do
    MAC=$(virsh dumpxml $instance | awk -F\' '/mac address/ {print $2}')
    IP=$(grep -B1 $MAC /var/lib/libvirt/dnsmasq/virbr0.status | head \
             -n 1 | awk '{print $2}' | sed -e s/\"//g -e s/,//)
    echo "virsh net-update default add ip-dhcp-host \"<host mac='$MAC' name='${instance}' ip='192.168.122.$var' />\" --live --config"
    var=$((var+1))
done

